version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # Optional, if you have custom nginx.conf
    networks:
      - sharednet
    
networks:
  sharednet:
